Working comments with datastore
chloemiranz/step pull request #5
Opened 2020-07-06 22:47 UTC by chloemiranz

2020-07-07 01:37 UTC, MrM117 requested changes

2020-07-07 01:37 UTC, MrM117 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +import com.google.appengine.api.datastore.Query.SortDirection;
Your import statements should be sorted alphabetically in two blocks: one block for static imports, one for the rest.  See https://google.github.io/styleguide/javaguide.html#s3.3-import-statements

2020-07-07 01:37 UTC, MrM117 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +  private String convertToJsonUsingGson(ArrayList<String> data) {
I don't think you're using this; just delete it.

2020-07-07 01:37 UTC, MrM117 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    return json;
nit: you could also just do `return gson.toJson(data)`

2020-07-07 01:37 UTC, MrM117 commented on portfolio/src/main/webapp/index.html
> +
nit: delete extra space (and below). The newline is fine, but no need for a space character.

2020-07-07 01:37 UTC, MrM117 commented on portfolio/src/main/webapp/script.js
> +
nit: delete extra space (and below)

2020-07-07 01:37 UTC, MrM117 commented on portfolio/src/main/webapp/script.js
> +} */
delete unused code

2020-07-07 01:37 UTC, MrM117 commented on portfolio/src/main/webapp/script.js
> +    //for (x in data) {
delete unused code

2020-07-07 01:37 UTC, MrM117 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +   private String convertToJson(String data) {
I don't think you need to convert a `String` to Json; typically, the point of converting data to Json is to serialize it (i.e., turn it into a string).

2020-07-07 01:37 UTC, MrM117 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    taskEntity.setProperty("comment", convertToJson(comment));
I don't think you need to convert the text to Json; you can just store it as-is.

2020-07-07 01:37 UTC, MrM117 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +      Object property = new Object();
You don't need to initialize `property` here, since you're never going to use the newly constructed `Object`.

2020-07-07 01:37 UTC, MrM117 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    String prettyJson;
I think these are unused; if so, delete.

2020-07-07 01:37 UTC, MrM117 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    //private ArrayList<String> comments = new ArrayList<String>();
Delete unused code.

2020-07-07 01:37 UTC, MrM117 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +      String comment = property.toString();
Simpler: I think you can just cast the result of getProperty: `String comment = (String) entity.getProperty("comment");`

2020-07-07 01:37 UTC, MrM117 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    List<String> tasks = new ArrayList<>();
rename `tasks` to `comments`

2020-07-07 01:37 UTC, MrM117 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
>      Entity taskEntity = new Entity("Task");
Better to give the entity a type of "Comment"

2020-07-07 19:57 UTC, MrM117 requested changes

2020-07-07 19:57 UTC, MrM117 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +import java.util.*;
nit: please import what you need explicitly. See https://google.github.io/styleguide/javaguide.html#s3.3.1-wildcard-imports

2020-07-07 19:57 UTC, MrM117 commented on portfolio/src/main/webapp/script.js
> +    const comments = document.getElementById('comments-container');
nit: might be better to rename `data` to `comments` and `comments` to `commentList` or something similar. See https://drive.google.com/file/d/1-VB6otFQRR2SOESwAXRCHiHiZ4tx11iw/view

2020-07-07 20:32 UTC, MrM117 requested changes

2020-07-07 20:32 UTC, MrM117 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +import java.util.*;
Oops, I wasn't clear. Please remove `import java.util.*;` and explicitly import what you need.

2020-07-07 21:26 UTC, MrM117 requested changes

2020-07-07 21:26 UTC, MrM117 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +import java.util.ArrayList;
So close! Just alphabetize (`ArrayList` before `List`).

FYI: setting up linting will catch this sort of thing for you. Here's a guide Chibuzo and Anthony followed; I'd recommend setting it up as soon as you're able: https://github.com/g-luo/step/blob/master/linting.md

2020-07-08 16:10 UTC, Ali09 approved these changes
LGTM

2020-07-08 19:47 UTC, MrM117 approved these changes
LGTM

Minor point: it would be better to add linting in a separate PR. See https://drive.google.com/file/d/1ITCt-1rY8LKgrKHwZSGuiyasMtpW7T_Q/preview

2020-07-09 00:05 UTC, merged